'Convert to Image using: https://plantuml.com/de/
@startuml

package "Examples" {
  package "data_control" {
    object Complex
    object JSON_Analyzer
    object LZW
    object QuadTree
    object Quaternion
    object Vectormath
  }
  package "graphics" {
   object AVI_Creator
   object CirclePackChart
   object ColorDialog
   object Graphics
   object LineEdit
   object Playingcards
   object SimpleChart
   object SunburstChart
   object Yeargrid
  }
  package "OpenGL" {
   object 0_Clear_Engine
   object Animation_Editor
   object Mapviewer
  }
  package "SDL2" {
   object Joystich_Demo
  }
  package "sound" {
   
  }
  package "TCP_IP" {
   object Modbus_Client
   object Modbus_Diagnostic
   object MQTT_Broker
   object MQTT_Publisher
   object Send_get_file
   object Socket
  }
  package "Wii" {
    object WiiMote
  }
}

package "External libs" 
{
  object Bass
  object DGLOpenGL
  object LNet 
  object MP_Arith
  object libSDL2
  object Synapse

  DGLOpenGL <|-- 0_Clear_Engine
  DGLOpenGL <|-- Animation_Editor 
  DGLOpenGL <|-- Mapviewer 
  Synapse <|-- Mapviewer 

  Joystich_Demo <|-- libSDL2

  LNet <|-- MQTT_Broker
  LNet <|-- MQTT_Publisher
  LNet <|-- Modbus_Client
  Synapse <|-- Modbus_Client
  LNet <|-- Modbus_Diagnostic
  Synapse <|-- Modbus_Diagnostic
  LNet <|-- Send_get_file
  LNet <|-- Socket

}

@enduml
