'Convert to Image using: https://plantuml.com/de/
@startuml

package "Examples" {
  package "OpenGL" {
   object Mapviewer
  }
  package "data_control" {
  }
  package "graphics" {
   object Sunburstchart
  }
  package "TCP_IP" {
   object Modbus_Diagnostic
  }
}

package "External libs" {
object Synapse
object LNet 
object MP_Arith
object DGLOpenGL
Synapse <|-- Mapviewer 
DGLOpenGL <|-- Mapviewer 
Synapse <|-- Modbus_Diagnostic
LNet <|-- Modbus_Diagnostic
}


@enduml
